title: VC Vocal
repository: restarea92/vcvocal
description: A sample site for VC Vocal project

markdown: GFM

plugins:
  - jekyll-gfm-admonitions
  - jekyll-optional-front-matter

exclude:
  - "**/*.ts"
  - "**/*.js"
  - "*.ts"
  - "*.js"
  - "*.json"
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/
